# Generated by Django 3.1.1 on 2021-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrackinginfo',
            name='is_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='cartrackinginfo',
            index=models.Index(fields=['timestamp', 'user_id'], name='car_trackin_timesta_5b0ca4_idx'),
        ),
    ]
