# Generated by Django 3.1.1 on 2020-10-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartrackinginfo',
            old_name='gas_status',
            new_name='gps_status',
        ),
    ]
