# Generated by Django 3.1.1 on 2021-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0002_auto_20210407_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='gas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='gps_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='odometer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
