# Generated by Django 3.1.1 on 2021-05-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0003_auto_20210514_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
