# Generated by Django 3.1.1 on 2021-05-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0004_auto_20210514_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrackinginfo',
            options={'ordering': ['timestamp']},
        ),
    ]
