# Generated by Django 3.1.1 on 2021-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0005_auto_20210514_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrackinginfo',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='gas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='odometer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
