# Generated by Django 3.1.1 on 2020-11-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0005_auto_20201023_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrackinginfo',
            options={'ordering': ['id']},
        ),
    ]
