# Generated by Django 3.1.1 on 2021-05-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0006_auto_20210520_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='speed',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
