# Generated by Django 3.1.1 on 2021-05-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0007_auto_20210528_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='distance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='speed',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=20),
        ),
    ]
