# Generated by Django 3.1.1 on 2021-05-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0008_auto_20210528_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrackinginfo',
            name='distance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
