# Generated by Django 3.1.1 on 2021-07-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_info', '0010_auto_20210528_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrackinginfo',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Tracking Info'},
        ),
    ]
