# Generated by Django 3.1.1 on 2020-11-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinatrackSettings',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='auth.user')),
                ('notification', models.BooleanField(choices=[(0, False), (1, True)], default=True)),
                ('language', models.CharField(choices=[(0, 'vi'), (1, 'en'), (2, 'cn')], default='vi', max_length=3)),
                ('map_display', models.CharField(choices=[(0, 'map'), (1, 'satellite')], default='map', max_length=128)),
                ('distance_unit', models.CharField(choices=[(0, 'YYYY-MM-DD HH:mm:ss'), (1, 'YYYY-DD-MM HH:mm:ss'), (2, 'YYYY-DD-MM HH:mm'), (3, 'YYYY/MM/DD HH:mm:ss'), (4, 'YYYY/DD/MM HH:mm:ss'), (5, 'YYYY/DD/MM HH:mm')], default='YYYY-MM-DD HH:mm:ss', max_length=256)),
                ('refresh_interval', models.IntegerField(choices=[(0, 10), (2, 20), (3, 30)], default=20)),
                ('theme', models.CharField(choices=[(0, 'dark'), (1, 'light')], default='light', max_length=64)),
            ],
            options={
                'db_table': 'settings',
                'ordering': ('id',),
            },
        ),
    ]
