# Generated by Django 3.1.1 on 2021-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plate_number',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['id'], name='user_profil_id_id_d7ea54_idx'),
        ),
    ]
