# Generated by Django 3.1.1 on 2021-01-30 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
