# Generated by Django 3.1.1 on 2021-01-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210130_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
