# Generated by Django 3.1.1 on 2021-04-07 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20210130_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image',
            field=models.ImageField(blank=True, default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
